-- AlterTable
ALTER TABLE `payment` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `payerRole` ENUM('LENDER', 'BORROWER', 'ADMIN') NOT NULL DEFAULT 'LENDER',
    ADD COLUMN `receiverRole` ENUM('LENDER', 'BORROWER', 'ADMIN') NOT NULL DEFAULT 'BORROWER';
